Document: awesomewm-desktop
Title: Debian awesomewm-desktop Manual
Author: <insert document author here>
Abstract: This manual describes what awesomewm-desktop is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/awesomewm-desktop/awesomewm-desktop.sgml.gz

Format: postscript
Files: /usr/share/doc/awesomewm-desktop/awesomewm-desktop.ps.gz

Format: text
Files: /usr/share/doc/awesomewm-desktop/awesomewm-desktop.text.gz

Format: HTML
Index: /usr/share/doc/awesomewm-desktop/html/index.html
Files: /usr/share/doc/awesomewm-desktop/html/*.html
